# Generated by Django 4.2.14 on 2024-08-06 11:27

import buddy_profiles.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Fullname')),
                ('picture_url', models.ImageField(blank=True, null=True, upload_to=buddy_profiles.models.upload_to)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Buddy Profile',
                'verbose_name_plural': 'Buddy Profiles',
                'ordering': ['full_name'],
            },
        ),
    ]
