# Generated by Django 4.2.14 on 2024-07-29 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyprofile',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buddyprofile',
            name='delete_date',
            field=models.DateField(auto_now=True, verbose_name='Deleted date'),
        ),
        migrations.AddField(
            model_name='buddyprofile',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Modified date'),
        ),
    ]
