# Generated by Django 4.2.14 on 2024-08-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddyprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'Buddy Profile', 'verbose_name_plural': 'Buddy Profiles'},
        ),
    ]
