# Generated by Django 4.2.14 on 2024-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0004_alter_buddyprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyprofile',
            name='delete_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deleted date'),
        ),
    ]
