# Generated by Django 4.2.14 on 2024-10-14 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyGroup',
            fields=[
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('buddy_profile_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile')),
                ('group_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin_a_member', models.BooleanField(default=False)),
                ('buddy_profile_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile')),
                ('group_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_admins',
            field=models.ManyToManyField(related_name='group_admins', through='buddy_groups.GroupAdmins', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', through='buddy_groups.GroupMembers', to='buddy_profiles.buddyprofile'),
        ),
    ]
