# Generated by Django 4.2.14 on 2024-07-31 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
        ('buddy_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('buddy_profile_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile')),
                ('group_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin_a_member', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('buddy_profile_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile')),
                ('group_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup')),
            ],
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_admins',
            field=models.ManyToManyField(related_name='group_admins', through='buddy_groups.GroupAdmins', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddygroup',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', through='buddy_groups.GroupMembers', to='buddy_profiles.buddyprofile'),
        ),
    ]
