# Generated by Django 4.2.14 on 2024-08-06 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddygroup',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='buddygroup',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted date'),
        ),
        migrations.AlterField(
            model_name='buddygroup',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupadmins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupadmins',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted date'),
        ),
        migrations.AlterField(
            model_name='groupadmins',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted date'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
