version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    env_file: .env.dev
    networks:
      net:
    volumes:
      - db_data:/var/lib/mysql
  web:
    build:
      context: "$PWD"
      dockerfile: Dockerfile.dev
    container_name: buddy-bill
    networks:
      net:
    volumes:
      - .:/billbudy
      - /billbudy/__pycache__/
    ports:
      - "8000:8000"
    depends_on:
      - db
networks:
  net:
volumes:
  db_data:
