version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py loaddata seeders/data.json &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/billbudy
      - /billbudy/__pycache__/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
