version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    env_file: .env.staging
    networks:
      - network_main_net
    ports:
      - "3306:3306"
    volumes:
      - db_data_stage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=billbuddy.settings.staging
      - DJANGO_ENV=staging
    build:
      context: "$PWD"
      dockerfile: Dockerfile.staging
    command: >
      sh -c "
          python manage.py wait_for_db --settings=billbuddy.settings.staging && \
          python manage.py makemigrations core users buddy_profiles buddy_groups buddy_expenses --settings=billbuddy.settings.staging && \
          python manage.py migrate --settings=billbuddy.settings.staging && \
          python manage.py flush --noinput --settings=billbuddy.settings.staging && \
          python manage.py loaddata seeders/data.json --settings=billbuddy.settings.staging && \
          python manage.py collectstatic --noinput && \
          python -m gunicorn --workers 3 --bind 0.0.0.0:8000 billbuddy.wsgi"
    container_name: buddy-bill
    networks:
      - network_main_net
    volumes:
      - .:/billbuddy
      - /billbuddy/__pycache__/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/billbuddy/static
      - media_volume:/billbuddy/media
    networks:
      - network_main_net
    ports:
      - "80:80"
    depends_on:
      - web
networks:
  network_main_net:
    name: network_main_net
volumes:
  db_data_stage:
  static_volume:
  media_volume:
