version: '3.8'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    env_file: .env.staging
    networks:
      - network_main_net
    ports:
      - "3306:3306"
    volumes:
      - db_data_stage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=billbuddy.settings.production
      - DJANGO_ENV=production
    build:
      context: "$PWD"
      dockerfile: Dockerfile.production
    command: >
      sh -c "
          python manage.py wait_for_db --settings=billbuddy.settings.production && \
          python manage.py makemigrations core users buddy_profiles buddy_groups buddy_expenses --settings=billbuddy.settings.production && \
          python manage.py migrate --settings=billbuddy.settings.production && \
          python manage.py flush --noinput --settings=billbuddy.settings.production && \
          python manage.py loaddata seeders/data.json --settings=billbuddy.settings.production && \
          python -m gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 120  billbuddy.wsgi:application"
    container_name: buddy-bill-production
    networks:
      - network_main_net
    restart: always
    volumes:
      - .:/billbuddy
      - /billbuddy/__pycache__/
      - static_volume:/billbuddy/static:rw
      - media_volume:/billbuddy/media:rw
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/billbuddy/static:rw
      - media_volume:/billbuddy/media:rw
    networks:
      - network_main_net
    ports:
      - "80:80"
    depends_on:
      - web
networks:
  network_main_net:
    name: network_main_net
volumes:
  db_data_stage:
  static_volume:
  media_volume:
