# Generated by Django 4.2.14 on 2024-07-30 22:18

import buddy_expenses.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_groups', '0001_initial'),
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Total amount')),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default=buddy_expenses.models.BuddyExpense.Currency['EUR'], max_length=64, verbose_name='Currencies')),
                ('type_payment_distribution', models.CharField(choices=[('EQUALLY', 'EQ'), ('UNEQUALLY', 'UNEQ'), ('PERCENTAGE', 'PER')], default=buddy_expenses.models.BuddyExpense.PaymentDistribution['EQ'], max_length=64, verbose_name='Type of distribution for payments of expenses')),
                ('evicende_picture_url', models.ImageField(blank=True, null=True, upload_to=buddy_expenses.models.upload_to)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('buddy_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup', verbose_name='Buddy group')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_payment', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Amount payment')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('buddy_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile', verbose_name='Buddy payer')),
            ],
        ),
        migrations.CreateModel(
            name='PayerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('what_expense_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense')),
                ('who_do_simple_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.simplepayment')),
            ],
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='payers',
            field=models.ManyToManyField(through='buddy_expenses.PayerPayments', to='buddy_expenses.simplepayment'),
        ),
    ]
