# Generated by Django 4.2.14 on 2024-07-30 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyexpense',
            name='payers',
            field=models.ManyToManyField(related_name='payer_simplepayment', through='buddy_expenses.PayerPayments', to='buddy_expenses.simplepayment'),
        ),
        migrations.CreateModel(
            name='SettleParticipantExpenseUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Deleted date')),
                ('what_expense_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense')),
                ('who_do_simple_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.simplepayment')),
            ],
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='participants',
            field=models.ManyToManyField(related_name='participants_simplepayment', through='buddy_expenses.SettleParticipantExpenseUp', to='buddy_expenses.simplepayment'),
        ),
    ]
