# Generated by Django 4.2.14 on 2024-08-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_profiles', '0001_initial'),
        ('buddy_groups', '0001_initial'),
        ('buddy_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settleparticipantexpenseup',
            name='who_settle_simple_payment_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='payerpayments',
            name='what_expense_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense'),
        ),
        migrations.AddField(
            model_name='payerpayments',
            name='who_do_simple_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='participantsofexpensepayment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_expenses.buddyexpense'),
        ),
        migrations.AddField(
            model_name='participantsofexpensepayment',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='buddy_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_groups.buddygroup', verbose_name='Buddy group'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='participants',
            field=models.ManyToManyField(related_name='participants_simplepayment', through='buddy_expenses.SettleParticipantExpenseUp', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='participants_of_expense_payment',
            field=models.ManyToManyField(related_name='participants_of_expense_payment', through='buddy_expenses.ParticipantsOfExpensePayment', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AddField(
            model_name='buddyexpense',
            name='payers',
            field=models.ManyToManyField(related_name='payer_simplepayment', through='buddy_expenses.PayerPayments', to='buddy_profiles.buddyprofile'),
        ),
    ]
