# Generated by Django 4.2.14 on 2024-07-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_expenses', '0002_alter_buddyexpense_payers_settleparticipantexpenseup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='simplepayment',
            name='amount_payment',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount payment'),
        ),
    ]
