# Generated by Django 4.2.14 on 2024-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_expenses', '0003_alter_buddyexpense_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='simplepayment',
            name='amount_payment',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Amount payment'),
        ),
    ]
