# Generated by Django 4.2.14 on 2024-08-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_expenses', '0005_participantsofexpensepayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payerpayments',
            old_name='what_expense_belong',
            new_name='what_expense_belong_to',
        ),
    ]
