# Generated by Django 4.2.14 on 2024-08-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_expenses', '0006_rename_what_expense_belong_payerpayments_what_expense_belong_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settleparticipantexpenseup',
            old_name='who_do_simple_payment',
            new_name='who_settle_simple_payment_up',
        ),
    ]
