# Generated by Django 4.2.14 on 2024-08-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
        ('buddy_expenses', '0008_alter_simplepayment_buddy_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepayment',
            name='buddy_payer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile', verbose_name='Buddy payer'),
        ),
    ]
