# Generated by Django 4.2.14 on 2024-08-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
        ('buddy_expenses', '0009_alter_simplepayment_buddy_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyexpense',
            name='participants_of_expense_payment',
            field=models.ManyToManyField(related_name='participants_of_expense_payment', through='buddy_expenses.ParticipantsOfExpensePayment', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AlterField(
            model_name='participantsofexpensepayment',
            name='group_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
    ]
