# Generated by Django 4.2.14 on 2024-08-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_profiles', '0003_alter_buddyprofile_options'),
        ('buddy_expenses', '0010_alter_buddyexpense_participants_of_expense_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerpayments',
            name='amount_payment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Amount payment'),
        ),
        migrations.AddField(
            model_name='settleparticipantexpenseup',
            name='amount_payment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Amount payment'),
        ),
        migrations.AlterField(
            model_name='buddyexpense',
            name='participants',
            field=models.ManyToManyField(related_name='participants_simplepayment', through='buddy_expenses.SettleParticipantExpenseUp', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AlterField(
            model_name='buddyexpense',
            name='payers',
            field=models.ManyToManyField(related_name='payer_simplepayment', through='buddy_expenses.PayerPayments', to='buddy_profiles.buddyprofile'),
        ),
        migrations.AlterField(
            model_name='buddyexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='participantsofexpensepayment',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Amount to pay'),
        ),
        migrations.AlterField(
            model_name='participantsofexpensepayment',
            name='payment_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Payment balance'),
        ),
        migrations.AlterField(
            model_name='payerpayments',
            name='who_do_simple_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.AlterField(
            model_name='settleparticipantexpenseup',
            name='who_settle_simple_payment_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_profiles.buddyprofile'),
        ),
        migrations.DeleteModel(
            name='SimplePayment',
        ),
    ]
